import Link from "next/link";
import Provider from "./Provider";
import Footer from "./Footer";
import Header from "./Header";
import Main from "./Main";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <Provider>
      <body>
       <Header />
        <Main>{children}</Main>
        <Footer />
      </body>
      </Provider>
    </html>
  );
}